import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Squter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Squter Ride is On
        </h1>

        <p className={styles.description}>
          Your Home Page is accessible here
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://dms.codes" className={styles.card}>
            <h2>DMS Codes Website</h2>
            <p>Main website of Digital Mind Solutions.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Who Build This App</h2>
            <p>Digital Mind Solutions did!</p>
            
          </a>

          <a
            href="https://github.com/squteronsquter"
            className={styles.card}
          >
            <h2>Visit our GitHub Space</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/"
            className={styles.card}
          >
            <h2>Ci/CD Deployment</h2>
            <p>
              We deployed this app with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://dms.codes"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
